# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [50]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [51]:
weather_csv = pd.read_csv(r'C:\Users\rzh00\Documents\gt-virt-atl-data-pt-09-2021-u-c-master\02-Homework\06-Python-APIs\Instructions\output_data\WeatherPy/weather_output.csv')
weather_csv

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hemi
0,0,Statesboro,32.4488,-81.7832,55.20,28,0,10.36,US,1642975530,north
1,1,Mataura,-46.1927,168.8643,57.47,50,51,1.32,NZ,1642975531,south
2,2,Kapaa,22.0752,-159.3190,79.12,72,20,3.00,US,1642975532,north
3,3,Carutapera,-1.1950,-46.0200,76.77,92,77,6.62,BR,1642975533,south
4,4,Mount Gambier,-37.8333,140.7667,76.26,40,78,3.18,AU,1642975533,south
...,...,...,...,...,...,...,...,...,...,...,...
571,571,Trofors,65.5333,13.4063,44.47,94,100,38.65,NO,1642975906,north
572,572,Aklavik,68.2191,-135.0107,2.01,98,96,4.88,CA,1642975907,north
573,573,Owando,-0.4819,15.8999,77.54,57,99,2.73,CG,1642975907,south
574,574,Elliot Lake,46.3834,-82.6331,5.27,83,71,6.55,CA,1642975908,north
575,575,Gobabis,-22.4500,18.9667,67.28,44,17,15.32,NaN,1642975909,south

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [52]:
# Configure GMaps
gmaps.configure(api_key = g_key)

# Use Lat and Lng as Locations
locations = weather_csv[['Lat', 'Lng']]

# Store Humidity
humidity = weather_csv['Humidity']

In [53]:
# Add Heatmap layer to map
fig = gmaps.figure()
max_intensity = np.max(humidity)


heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating = False, max_intensity = 100, point_radius = 3)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [54]:
# Clean df based on given weather conditions
clean_df = weather_csv[(weather_csv['Max Temp'] < 80) & (weather_csv['Max Temp'] > 70) & (weather_csv['Wind Speed'] < 10) &
                     (weather_csv['Cloudiness'] == 0)].dropna().reset_index().drop(columns = {'index'})
clean_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hemi
0,45,Mar del Plata,-38.0023,-57.5575,78.82,58,0,8.01,AR,1642975558,south
1,145,Port Elizabeth,-33.9180,25.5701,72.10,80,0,5.30,ZA,1642975627,south
2,281,Harper,4.3750,-7.7169,78.80,84,0,7.76,LR,1642975717,north
3,313,San Isidro,-12.1167,-77.0500,76.59,65,0,8.05,PE,1642975739,south
4,344,Lompoc,34.6391,-120.4579,76.69,52,0,9.22,US,1642975760,north
5,370,Fortuna,40.5982,-124.1573,70.93,53,0,1.01,US,1642975777,north
6,379,Clovis,36.8252,-119.7029,72.12,48,0,1.99,US,1642975680,north
7,423,Ca Mau,9.1769,105.1500,72.05,91,0,1.45,VN,1642975811,north
8,525,Conde,-7.2597,-34.9075,78.26,83,0,4.61,BR,1642975876,south
9,533,Bac Lieu,9.2850,105.7244,73.76,89,0,3.91,VN,1642975881,north
10,534,Plettenberg Bay,-34.0527,23.3716,73.49,52,0,8.79,ZA,1642975882,south

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [55]:
# Create Hotel DF
hotel_df = clean_df.loc[:, ["City", "Country", "Lat", "Lng"]]
# Add hotel column
hotel_df['Hotel Name'] = ''

In [56]:
# Establish parameters
params = {
    'keyword' : 'hotel',
    'radius' : 5000,
    'key' : g_key
}

# Create Base URL
base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

for index, row in hotel_df.iterrows():

    lat = row['Lat']
    lng = row['Lng']
    city = row['City']
    params["location"] = f"{lat},{lng}"
    
    print(f"Begin search in {row['City']}...")
    response = requests.get(base_url, params = params).json()
        
    results = response['results']
        
    try:
        print(f"The closest hotel in {city} is {results[0]['name']}")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
        
    except(KeyError, IndexError):
        print("Missing information. Moving on...")
    
        
print('---------------------')
print('End Data Collection')
print('---------------------')

Begin search in Mar del Plata...
The closest hotel in Mar del Plata is Sheraton Mar del Plata Hotel
Begin search in Port Elizabeth...
The closest hotel in Port Elizabeth is The Grand Hotel
Begin search in Harper...
Missing information. Moving on...
Begin search in San Isidro...
The closest hotel in San Isidro is Westin Lima Hotel & Convention Center
Begin search in Lompoc...
The closest hotel in Lompoc is SureStay Plus Hotel By Best Western Lompoc
Begin search in Fortuna...
The closest hotel in Fortuna is The Redwood Riverwalk, A Boutique Motel
Begin search in Clovis...
The closest hotel in Clovis is Holiday Inn Express & Suites Clovis-Fresno Area, an IHG Hotel
Begin search in Ca Mau...
The closest hotel in Ca Mau is Khách Sạn Mường Thanh Luxury Cà Mau
Begin search in Conde...
Missing information. Moving on...
Begin search in Bac Lieu...
The closest hotel in Bac Lieu is New Palace Hotel
Begin search in Plettenberg Bay...
The closest hotel in Plettenberg Bay is Bayview Hotel
---------------------
End Data Collection
---------------------

In [57]:
hotel_df

,City,Country,Lat,Lng,Hotel Name
0,Mar del Plata,AR,-38.0023,-57.5575,Sheraton Mar del Plata Hotel
1,Port Elizabeth,ZA,-33.9180,25.5701,The Grand Hotel
2,Harper,LR,4.3750,-7.7169,
3,San Isidro,PE,-12.1167,-77.0500,Westin Lima Hotel & Convention Center
4,Lompoc,US,34.6391,-120.4579,SureStay Plus Hotel By Best Western Lompoc
5,Fortuna,US,40.5982,-124.1573,"The Redwood Riverwalk, A Boutique Motel"
6,Clovis,US,36.8252,-119.7029,Holiday Inn Express & Suites Clovis-Fresno Are...
7,Ca Mau,VN,9.1769,105.1500,Khách Sạn Mường Thanh Luxury Cà Mau
8,Conde,BR,-7.2597,-34.9075,
9,Bac Lieu,VN,9.2850,105.7244,New Palace Hotel
10,Plettenberg Bay,ZA,-34.0527,23.3716,Bayview Hotel

In [58]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [59]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))